spring.datasource.url=jdbc:mariadb://192.168.16.3:3306/LoveCode
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update